export interface IBrowserCapabilities {
    IS_NODE: boolean;
    isTest: boolean;
    ie: boolean;
    ielt9: boolean;
    edge: boolean;
    webkit: boolean;
    gecko: boolean;
    android: boolean;
    android23: boolean;
    chrome: boolean;
    chromeVersion: string;
    safari: boolean;
    phantomjs: boolean;
    ie3d: boolean;
    webkit3d: boolean;
    opera12: boolean;
    gecko3d: boolean;
    any3d: boolean;
    iosWeixin: boolean;
    mobile: boolean;
    mobileWebkit: boolean;
    mobileWebkit3d: boolean;
    mobileOpera: boolean;
    mobileGecko: boolean;
    touch: boolean;
    msPointer: boolean;
    pointer: boolean;
    retina: boolean;
    devicePixelRatio: number;
    language: string;
    ie9: boolean;
    ie10: boolean;
    webgl: boolean;
    imageBitMap: boolean;
    resizeObserver: boolean;
    btoa: boolean;
    decodeImageInWorker: boolean;
    monitorDPRChange: boolean;
    supportsPassive: boolean;
    proxy: boolean;
    requestIdleCallback: boolean;
    checkDevicePixelRatio: () => boolean;
}
declare const Browser: IBrowserCapabilities;
export default Browser;
