import { Map } from "./index";
import { LngLatLike } from '../types';
import { getLocalFromMouse } from '../utils/tilemaputils';
import { BaseEventMap } from '../core/event';

/**
 * @category Map
 */
export interface DomEventMap extends BaseEventMap<Map> {
    /** 
     * Geographic coordinate of the event (optional)
     * 事件的地理坐标（可选） 
     */
    coordinate?: LngLatLike;
}

/**
 * Supported DOM event types list
 * 支持的DOM事件类型列表
 */
const eventMaps = [
    'click',        // Click 点击
    'dblclick',     // Double click 双击
    'mousedown',    // Mouse down 鼠标按下
    'mouseup',      // Mouse up 鼠标释放
    'mousemove',    // Mouse move 鼠标移动
    'mouseenter',   // Mouse enter element (no bubbling) 鼠标进入元素（不冒泡）
    'mouseleave',   // Mouse leave element (no bubbling) 鼠标离开元素（不冒泡）
    'mouseover',    // Mouse enter element (bubbling) 鼠标进入元素（冒泡）
    'mouseout',     // Mouse leave element (bubbling) 鼠标离开元素（冒泡）
]

/**
 * Extend Map class type definition
 * 扩展Map类的类型定义
 */
declare module "./index" {
    interface Map {
        /**
         * @internal
         * Remove all DOM event listeners
         * 移除所有DOM事件监听
         */
        _removeDomEvents(): void;
        /**
         * @internal
         * Register DOM event listeners
         * 注册DOM事件监听
         */
        _registerDomEvents(): void;
    }
}

/**
 * @internal
 * Remove all DOM event listeners
 * 移除所有DOM事件监听
 */
Map.prototype._removeDomEvents = function (this: Map) {
    // console.log('removeDomEvents', this)
}

/**
 * @internal
 * Register DOM event listeners
 * 注册DOM事件监听
 * 
 * This method adds various mouse event listeners to the map container element,
 * and converts events to map coordinates before triggering corresponding events.
 * 该方法会为地图容器元素添加各种鼠标事件监听，
 * 并将事件转换为地图坐标后触发对应事件
 */
Map.prototype._registerDomEvents = function (this: Map) {
    const domElement = this.sceneRenderer.container;
    if (domElement) {
        // Simple "drag vs click" judgment: down position + displacement threshold
        // 简单的“拖拽 vs 点击”判定：按下位置 + 位移阈值
        const MOVE_THRESHOLD = 5; // Unit: pixels 单位：像素
        let lastDownPos: { x: number; y: number } | null = null;

        eventMaps.forEach(eventName => {
            domElement.addEventListener(eventName as any, (evt: any) => {
                // Safety check: if sceneRenderer is destroyed, return directly
                // 安全检查：如果sceneRenderer已销毁，直接返回
                if (!this.sceneRenderer) {
                    return;
                }

                // Record down position
                // 记录按下位置
                if (eventName === 'mousedown') {
                    lastDownPos = {
                        x: evt.clientX,
                        y: evt.clientY
                    };
                }

                // Judge drag for click: if moved distance is too large, consider it as click generated by drag, ignore directly
                // 对 click 做拖拽判断：如果移动距离过大，则认为是拖拽产生的 click，直接忽略
                if (eventName === 'click' && lastDownPos) {
                    const dx = evt.clientX - lastDownPos.x;
                    const dy = evt.clientY - lastDownPos.y;
                    const dist = Math.sqrt(dx * dx + dy * dy);
                    if (dist > MOVE_THRESHOLD) {
                        // Consider as drag, do not trigger map click event
                        // 认为是拖拽，不触发 map 的 click 事件
                        return;
                    }
                }

                let latlnt = getLocalFromMouse(evt, this, this.sceneRenderer.camera);
                let eventData: DomEventMap = {
                    target: this,
                    originEvent: evt,
                    eventName: eventName,
                    screenXY: {
                        X: evt.screenX,
                        Y: evt.screenY,
                    }
                };
                if (latlnt) {
                    let coordinate: LngLatLike = [latlnt.x, latlnt.y, latlnt.z];
                    eventData = {
                        target: this,
                        originEvent: evt,
                        coordinate: coordinate,
                        eventName: eventName,
                        screenXY: {
                            X: evt.screenX,
                            Y: evt.screenY,
                        }
                    }
                }
                this.fire(eventName, eventData);
            });
        })
    }
}

// Automatically register DOM events after Map loads
// 在Map加载完成后自动注册DOM事件
Map.addOnLoadHook('_registerDomEvents');
